/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.oxisto.reticulated

import com.github.oxisto.reticulated.ast.Visitor
import org.antlr.v4.runtime.CharStreams
import com.github.oxisto.reticulated.grammar.Python3Lexer
import com.github.oxisto.reticulated.grammar.Python3Parser
import org.antlr.v4.runtime.CommonTokenStream

class App {
  val greeting: String
    get() {
      return "Hello world."
    }
}

fun main(args: Array<String>) {
  val inputStream = CharStreams.fromStream(App::class.java.getResourceAsStream("/main.py"));
  val lexer = Python3Lexer(inputStream);
  val tokenStream = CommonTokenStream(lexer);
  val parser = Python3Parser(tokenStream);

  val ctx = parser.file_input();

  val fileInput = ctx.accept(Visitor());

  System.out.println(fileInput);

  println(App().greeting)
}
