/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.oxisto.reticulated

import io.github.oxisto.reticulated.ast.FileInput
import io.github.oxisto.reticulated.ast.Scope
import io.github.oxisto.reticulated.ast.Visitor
import io.github.oxisto.reticulated.grammar.Python3Lexer
import io.github.oxisto.reticulated.grammar.Python3Parser
import org.antlr.v4.runtime.CharStreams
import org.antlr.v4.runtime.CommonTokenStream

class PythonParser {

  fun parse(path: String): ParserResult {
    val inputStream = CharStreams.fromFileName(path)
    val lexer = Python3Lexer(inputStream)
    val tokenStream = CommonTokenStream(lexer)
    val parser = Python3Parser(tokenStream)

    val ctx = parser.file_input()

    // new global scope
    val global = Scope()

    val fileInput = ctx.accept(Visitor(global)) as FileInput

    return ParserResult(fileInput, global)
  }
}

